apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: kube-system
type: Opaque
stringData:
 # Panorama Auth Key
  PAN_PANORAMA_AUTH_KEY: "474621752056996"
  #PAN_PANORAMA_AUTH_KEY: "_AQ__f0MHdF9Wks5ryh_Qe9l6CMvZCQ"
  # Thermite Certificate retrieval 
  CN-SERIES-AUTO-REGISTRATION-PIN-ID: "1269010e-5dd5-4bc8-854a-207689e712cd"
  CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: "9e5a6d08d1b44902b7772e52a7ae5f79"
#Non-mandatory parameters
  # Uncomment this for CSP overide 
  #CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>" 
